# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'appDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  # Pods for appDemo

  target 'appDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appDemoUITests' do
    # Pods for testing
  end

end
